name: Docker Actions

on:
  push:
    paths:
      - "**.py"
      - "**.yml"
      - "**.yaml"
    branches:
      - main
jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: docker compose -f test/compose.yaml up -d
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip

      - name: Install dependecies
        run: pip install -r requirements.txt
        
      - name: Tests
        run: sh test.sh
